/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductOrgProductRouteImport } from './routes/product.$org.$product'
import { Route as ProductOrgProductIndexRouteImport } from './routes/product.$org.$product.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductOrgProductRoute = ProductOrgProductRouteImport.update({
  id: '/product/$org/$product',
  path: '/product/$org/$product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductOrgProductIndexRoute = ProductOrgProductIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductOrgProductRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/$org/$product': typeof ProductOrgProductRouteWithChildren
  '/product/$org/$product/': typeof ProductOrgProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$org/$product': typeof ProductOrgProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/$org/$product': typeof ProductOrgProductRouteWithChildren
  '/product/$org/$product/': typeof ProductOrgProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product/$org/$product' | '/product/$org/$product/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product/$org/$product'
  id: '__root__' | '/' | '/product/$org/$product' | '/product/$org/$product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductOrgProductRoute: typeof ProductOrgProductRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$org/$product': {
      id: '/product/$org/$product'
      path: '/product/$org/$product'
      fullPath: '/product/$org/$product'
      preLoaderRoute: typeof ProductOrgProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$org/$product/': {
      id: '/product/$org/$product/'
      path: '/'
      fullPath: '/product/$org/$product/'
      preLoaderRoute: typeof ProductOrgProductIndexRouteImport
      parentRoute: typeof ProductOrgProductRoute
    }
  }
}

interface ProductOrgProductRouteChildren {
  ProductOrgProductIndexRoute: typeof ProductOrgProductIndexRoute
}

const ProductOrgProductRouteChildren: ProductOrgProductRouteChildren = {
  ProductOrgProductIndexRoute: ProductOrgProductIndexRoute,
}

const ProductOrgProductRouteWithChildren =
  ProductOrgProductRoute._addFileChildren(ProductOrgProductRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductOrgProductRoute: ProductOrgProductRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
